.github/workflows/release.yaml, .goreleaser.yaml
Setup Notarization Steps. 
@joaopalet Publishing of the Notarised artifacts is missing.
=> Setup Notarization Pipeline

internal/cmd/service-account/key/create/create.go
- To support use case of saving the result of service-account key creation directly in a file
=> Send service account key creation to stderr

docs/stackit_mongodbflex_instance_create.md, docs/stackit_mongodbflex_instance_update.md, docs/stackit_mongodbflex_user_create.md, docs/stackit_mongodbflex_user_update.md, docs/stackit_postgresflex_user_create.md, docs/stackit_postgresflex_user_update.md, internal/cmd/mongodbflex/user/create/create.go, internal/cmd/mongodbflex/user/create/create_test.go, internal/cmd/mongodbflex/user/update/update.go, internal/cmd/mongodbflex/user/update/update_test.go, internal/cmd/postgresflex/user/create/create.go, internal/cmd/postgresflex/user/create/create_test.go, internal/cmd/postgresflex/user/delete/delete.go, internal/cmd/postgresflex/user/delete/delete_test.go, internal/cmd/postgresflex/user/describe/describe.go, internal/cmd/postgresflex/user/describe/describe_test.go, internal/cmd/postgresflex/user/reset-password/reset_password.go, internal/cmd/postgresflex/user/reset-password/reset_password_test.go, internal/cmd/postgresflex/user/update/update.go, internal/cmd/postgresflex/user/update/update_test.go, internal/pkg/args/args.go, internal/pkg/args/args_test.go
- Fix roles available
- Make `--username` flag required on creation
- Change `--roles` flag name to `--role`
- Remove incorrect UUID check of user ID
- Add check for args, check if args aren't empty
=> Postgresflex user fixes

docs/stackit_curl.md, internal/cmd/curl/curl.go, internal/cmd/ske/cluster/update/update.go
- Improve `curl` examples and error message
- Add prompt for confirmation before `ske cluster update`
=> Improvements to `curl` and `ske` commands

docs/stackit_organization_member_list.md, docs/stackit_service-account_token_create.md, internal/cmd/organization/member/list/list.go, internal/cmd/service-account/delete/delete.go, internal/cmd/service-account/key/create/create.go, internal/cmd/service-account/token/create/create.go, internal/pkg/auth/user_token_flow.go
`auth`
- add user-friendly message to failed because of invalid storage key
`organization`
- fix examples
`service-account`
- fix example
- fix messages
=> Auth, organization and service account fixes

docs/stackit_dns_zone_list.md, internal/cmd/dns/zone/list/list.go, internal/cmd/dns/zone/list/list_test.go
- Flag `--deleted` (if set, would show deleted zones only; if unset, would show non-deleted zones only) replaced by `--include-deleted` (if set, shows all zones; if unset, shows non-deleted zones only)
- Remove flag `--inactive` showing deleted zones when `--deleted` isn't set
=> Change flag behavior in "dns zone list"

INSTALLATION.md
Using `go install` has some known issues such as:
- Binary is called `stackit-cli` because that has to be name of the Go module
- Version returned in `--version` is "DEV" as the actual version is only set when building the binaries using GoReleaser
=> Docs: Remove `go install` recommendation from guide

internal/cmd/ske/cluster/create/create_test.go, internal/cmd/ske/cluster/update/update_test.go
SKE will soon deprecate the old flatcar version, so we should update it before the test will fail.
=> SKE: update flatcar version in tests

.goreleaser.yaml
Go releaser has been updated to prevent the pre release uploads to Homebrew.
=> Skip pre release uploads to homebrew

.aptly.conf, .github/workflows/ci.yaml, .github/workflows/release.yaml, .goreleaser.yaml, scripts/publish-apt-packages.sh
- Give GPG key fingerprint instead of key ID to Aptly for the signing of the release
- Even though Aptly specifies in the [docs](https://www.aptly.info/doc/aptly/publish/snapshot/) that `gpg-key` expects a key ID, it actually expects a key fingerprint
- Disable the [key database daemon](https://github.com/gpg/gnupg/blob/master/README) (`keyboxd`):
- Since version 2.3.0 of `gnupg` all imported keys are stored in a SQLite database instead of using the specified keyring, and we need to import the key to a custom keyring to use them with Aptly
- Rename Linux package name to `stackit`
- Make APT distribution name consistent across all steps of the script
- Removes `rootDir` from custom Aptly config file (as defaults to the default value)
- Improve comment and job name of workflow
=> Fixes to publishing of DEB packages to APT repo

.github/workflows/release.yaml, .goreleaser.yaml
Final testing phase in preparation for the first Beta `v0.1.0` release
=> Temporarily publish prereleases to package managers

.goreleaser.yaml
=> Mark GitHub releases as "Pre-release" for prerelease tags

internal/pkg/flags/cidrslice.go, internal/pkg/flags/flags_test.go
Allow users to specify an empty CIDR slice by setting the flag to `""`.
E.g. `stackit <service> instance update <instance ID> --acl ""` sets the ACLs of the instance to the empty list.
This makes the custom flag `CIDRSliceFlag` have the same behaviour for empty values as the more generic and default `StringSlice` flag type
=> Allow specifying empty list for CIDRSliceFlag

internal/pkg/auth/user_login.go
fixes #80.
This PR tries to address the issue of a fixed redirect port by choosing a random free one.
Screenshot:
=> auth: login: use next free port

internal/cmd/mariadb/instance/update/update_test.go, internal/cmd/mongodbflex/instance/update/update_test.go, internal/cmd/opensearch/instance/update/update_test.go, internal/cmd/postgresflex/instance/update/update_test.go, internal/cmd/rabbitmq/instance/update/update_test.go, internal/cmd/redis/instance/update/update_test.go
This tests that not specifying an `--acl` flag when updating instances is mapped to a `nil` ACL in the input model, so we don't set the instance ACL to an empty list (this would be achieved by setting `--acl ""`)
=> Extend unit tests of updates using CIDRSliceFlag

internal/cmd/config/unset/unset.go, internal/cmd/config/unset/unset_test.go, internal/pkg/config/config.go, internal/pkg/globalflags/global_flags.go
**PR to `feature-logging-debug` branch**
- Adds global verbosity flag
- Still has no effect when set, will be added over next PRs
=> Add global verbosity flag

internal/pkg/config/config.go
- Addresses #153 
- We only need to **write** the `Viper` configuration to the config file on `stackit config set/unset` it is persisted
- For other cases, it's enough to set the defaults (for empty keys) or simply **read** the previously set values from the config file
=> Only write to config file when needed

docs/stackit_ske.md, docs/stackit_ske_credentials.md, docs/stackit_ske_credentials_complete-rotation.md, docs/stackit_ske_credentials_start-rotation.md, docs/stackit_ske_kubeconfig.md, docs/stackit_ske_kubeconfig_create.md, internal/cmd/ske/kubeconfig/create/create.go, internal/cmd/ske/kubeconfig/create/create_test.go, internal/cmd/ske/kubeconfig/kubeconfig.go, internal/cmd/ske/ske.go, internal/pkg/services/ske/utils/utils.go, internal/pkg/services/ske/utils/utils_test.go
This command is creating a kubeconfig and writing it to a file. By default, this location is ~/.kube/config (which is default for kubernetes) but can be changed via flag.
This choice is informed by behavior in GCP and AWS:
- https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html#create-kubeconfig-automatically
- https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials
When setting the expiration time, I created a helper function to save the user from writing large timeouts (eg. 3 months) in seconds (the unit the API ingests)
=> SKE Credentials Rotation: kubeconfig create command

INSTALLATION.md
- Reverts stackitcloud/stackit-cli#162
- Adjusts URL to new domain
=> Re-add APT installation instructions with new domain

internal/pkg/services/argus/utils/utils.go, internal/pkg/services/argus/utils/utils_test.go
- This will be used by the new `argus grafana single-sign-on enable/disable` and `argus grafana public-read-access enable/disable` commands
- The update endpoint is a `PUT` and contains all Grafana configs, and since we want to have separate commands for the setting above, we need to first get the current configs of the instance and adjust them according to the command (simulate a `PATCH` update)
- `GetPartialUpdateGrafanaConfigsPayload` will then be called e.g. as `GetPartialUpdateGrafanaConfigsPayload(<ctx>, <client>, <instanceId>, <projectId>, true, nil)` for the `argus grafana single-sign-on enable` command
=> Add util for `argus grafana` configuration commands

INSTALLATION.md
This PR adds the [repology](https://repology.org/) [packaging status badge](https://repology.org/project/stackit-cli/badges) for the STACKIT CLI to the `INSTALLATION.md`.
This allows future users to quickly see which (native/official) repositories have the STACKIT CLI packaged and enables a fast installation using their most favorite package manager.
In the future, we can increase the `columns` parameter once the list gets too long.
=> Add repology packaging status badge to INSTALLATION.md

internal/cmd/config/list/list.go, internal/cmd/config/set/set.go, internal/cmd/config/unset/unset.go, internal/pkg/auth/storage.go, internal/pkg/config/config.go, internal/pkg/projectname/project_name.go
This PR tries to solve #153 by only creating the config file & directory on commands that actually need to write the config, e.g., `set` & `unset`.
Every command that needs to write the config should now use the `config.Write` function instead of directly calling `viper.WriteConfig`. The `config.Write` function ensures that the config directory exists and creates it if necessary. Oddly, `viper` doesn't support this out of the box...
I additionally found that `viper.WriteConfig` also writes the default values (set with `viper.SetDefault`) to the config. This means that the defaults are not being used after the config file is first written. I don't think that's something we can/should easily change, but we should definitely keep it in mind that future default changes might not reach the …
=> Change config handling: only create config file & directory if needed

docs/stackit_argus_grafana_describe.md, internal/cmd/argus/grafana/describe/describe.go, internal/cmd/argus/grafana/describe/describe_test.go, internal/cmd/argus/grafana/single-sign-on/single_sign_on.go
- Move instance ID to argument in `argus grafana describe` command
- Add `sso` alias for `single-sign-on` command
=> Improvements for `argus grafana` commands

internal/cmd/postgresflex/instance/clone/clone.go, internal/cmd/postgresflex/instance/clone/clone_test.go
time.RFC3339 truncates the time zone, when zone is given as 00:00.
=> Change recovery date format for PostgresFlex clone command

docs/stackit_config.md, go.mod, internal/cmd/config/config.go
Includes a `go mod tidy` that was missed in the previous PR
=> Document config file location in command

internal/cmd/load-balancer/describe/describe.go, internal/cmd/load-balancer/observability-credentials/add/add.go, internal/cmd/load-balancer/observability-credentials/describe/describe.go
- Also prompt for password when adding credentials before prompting for confirmation
=> Make pretty the default output for LB describe commands

internal/pkg/config/config.go, internal/pkg/config/profiles.go
- With this it's already possible to use profiles, but we need to create the folder and file manually
- In a following PR I will implement the `stackit config profile set/unset` commands
=> Choose config folder based on profile in InitConfig

.goreleaser.yaml, docs/stackit_config.md, docs/stackit_config_profile.md, docs/stackit_config_profile_set.md, docs/stackit_config_profile_unset.md, docs/stackit_load-balancer_observability-credentials.md, docs/stackit_load-balancer_observability-credentials_cleanup.md, docs/stackit_load-balancer_observability-credentials_list.md, internal/cmd/config/list/list.go, internal/cmd/config/profile/set/set.go, internal/cmd/config/profile/unset/unset.go, internal/cmd/load-balancer/describe/describe.go, internal/cmd/load-balancer/observability-credentials/cleanup/cleanup.go, internal/cmd/load-balancer/observability-credentials/cleanup/cleanup_test.go, internal/cmd/load-balancer/observability-credentials/list/list.go, internal/cmd/load-balancer/observability-credentials/observability-credentials.go, internal/cmd/load-balancer/target-pool/add-target/add_target_test.go, internal/cmd/load-balancer/target-pool/remove-target/remove_target_test.go, internal/cmd/mongodbflex/options/options.go, internal/cmd/postgresflex/options/options.go, internal/cmd/root.go, internal/cmd/ske/options/options.go, internal/pkg/config/config.go, internal/pkg/config/profiles.go, internal/pkg/print/print.go, internal/pkg/print/print_test.go, internal/pkg/services/load-balancer/utils/utils.go, internal/pkg/services/load-balancer/utils/utils_test.go, internal/pkg/tables/tables.go
- Add table titles to `config set` command
- Add debug logs to `config profile set/unset`
- Fix setting a new profile when there is a currently active profile
Only two last commits are relevant, the rest is just bringing the latest changes from main
=> Improvements to profiles functionality

internal/cmd/ske/options/options.go
=> Filter ske options json and yaml output

internal/cmd/root.go, internal/pkg/print/print.go
=> Color errors and warnings

internal/cmd/object-storage/bucket/create/create.go, internal/cmd/ske/cluster/create/create.go, internal/pkg/errors/errors.go, internal/pkg/services/object-storage/utils/utils.go, internal/pkg/services/object-storage/utils/utils_test.go, internal/pkg/services/ske/utils/utils.go, internal/pkg/services/ske/utils/utils_test.go
- Also fixes the check in SKE and uniformizes the approaches
=> Check for service enablement before bucket creation

docs/stackit_beta_server_backup.md, docs/stackit_beta_server_backup_create.md, docs/stackit_beta_server_backup_delete.md, docs/stackit_beta_server_backup_describe.md, docs/stackit_beta_server_backup_list.md, docs/stackit_beta_server_backup_restore.md, docs/stackit_beta_server_backup_schedule_create.md, docs/stackit_beta_server_backup_schedule_update.md, docs/stackit_beta_server_backup_volume-backup.md, docs/stackit_beta_server_backup_volume-backup_delete.md, docs/stackit_beta_server_backup_volume-backup_restore.md, internal/cmd/beta/server/backup/backup.go, internal/cmd/beta/server/backup/create/create.go, internal/cmd/beta/server/backup/create/create_test.go, internal/cmd/beta/server/backup/delete/delete.go, internal/cmd/beta/server/backup/delete/delete_test.go, internal/cmd/beta/server/backup/describe/describe.go, internal/cmd/beta/server/backup/describe/describe_test.go, internal/cmd/beta/server/backup/list/list.go, internal/cmd/beta/server/backup/list/list_test.go, internal/cmd/beta/server/backup/restore/restore.go, internal/cmd/beta/server/backup/restore/restore_test.go, internal/cmd/beta/server/backup/schedule/update/update.go, internal/cmd/beta/server/backup/schedule/update/update_test.go, internal/cmd/beta/server/backup/volume-backup/delete/delete.go, internal/cmd/beta/server/backup/volume-backup/delete/delete_test.go, internal/cmd/beta/server/backup/volume-backup/restore/restore.go, internal/cmd/beta/server/backup/volume-backup/restore/restore_test.go, internal/cmd/beta/server/backup/volume-backup/volumebackup.go
adds various `server backup` subcommands
Testing Done:
* tested locally
* ran linters / formatters / `make test` / `make generate-docs`
=> ref 644868 - server backup subcommands

docs/stackit_beta_sqlserverflex_database.md, docs/stackit_beta_sqlserverflex_database_describe.md, docs/stackit_beta_sqlserverflex_database_list.md, docs/stackit_beta_sqlserverflex_user_create.md, go.mod, go.sum, internal/cmd/beta/sqlserverflex/database/create/create.go, internal/cmd/beta/sqlserverflex/database/create/create_test.go, internal/cmd/beta/sqlserverflex/database/database.go, internal/cmd/beta/sqlserverflex/database/describe/describe.go, internal/cmd/beta/sqlserverflex/database/describe/describe_test.go, internal/cmd/beta/sqlserverflex/database/list/list.go, internal/cmd/beta/sqlserverflex/database/list/list_test.go, internal/cmd/beta/sqlserverflex/user/create/create.go, internal/cmd/beta/sqlserverflex/user/create/create_test.go, internal/cmd/beta/sqlserverflex/user/describe/describe.go, internal/pkg/services/sqlserverflex/utils/utils_test.go
- Also updates `sqlserverflex` SDK module to `v0.3.0`
=> Implement `sqlserverflex database list/describe` commands

docs/stackit_beta_server_command.md, docs/stackit_beta_server_command_create.md, docs/stackit_beta_server_command_describe.md, docs/stackit_beta_server_command_list.md, docs/stackit_beta_server_command_template.md, docs/stackit_beta_server_command_template_describe.md, docs/stackit_beta_server_command_template_list.md, docs/stackit_config_set.md, docs/stackit_config_unset.md, go.mod, go.sum, internal/cmd/beta/server/command/command.go, internal/cmd/beta/server/command/create/create.go, internal/cmd/beta/server/command/create/create_test.go, internal/cmd/beta/server/command/describe/describe.go, internal/cmd/beta/server/command/describe/describe_test.go, internal/cmd/beta/server/command/list/list.go, internal/cmd/beta/server/command/list/list_test.go, internal/cmd/beta/server/command/template/describe/describe.go, internal/cmd/beta/server/command/template/describe/describe_test.go, internal/cmd/beta/server/command/template/list/list.go, internal/cmd/beta/server/command/template/list/list_test.go, internal/cmd/beta/server/command/template/template.go, internal/cmd/config/set/set.go, internal/cmd/config/unset/unset.go, internal/cmd/config/unset/unset_test.go, internal/pkg/config/config.go, internal/pkg/services/runcommand/client/client.go, internal/pkg/services/runcommand/utils/utils.go, internal/pkg/services/runcommand/utils/utils_test.go
adds `stackit beta server command ...`
Testing Done:
tested locally. ran linters/formatters/tests/doc generators
=> ref 644499 - server command

docs/stackit_beta_network-area_route.md, docs/stackit_beta_network-area_route_create.md, docs/stackit_beta_network-area_route_update.md, internal/cmd/beta/network-area/route/create/create.go, internal/cmd/beta/network-area/route/create/create_test.go, internal/cmd/beta/network-area/route/routes.go, internal/cmd/beta/network-area/route/update/update.go, internal/cmd/beta/network-area/route/update/update_test.go
Support to update labels for a network-area route.
=> Add update command to network-area route

docs/stackit_beta_server.md, docs/stackit_beta_server_volume.md, docs/stackit_beta_server_volume_attach.md, docs/stackit_beta_server_volume_describe.md, docs/stackit_beta_server_volume_detach.md, docs/stackit_beta_server_volume_list.md, docs/stackit_beta_server_volume_update.md, internal/cmd/beta/server/server.go, internal/cmd/beta/server/volume/attach/attach.go, internal/cmd/beta/server/volume/attach/attach_test.go, internal/cmd/beta/server/volume/describe/describe.go, internal/cmd/beta/server/volume/describe/describe_test.go, internal/cmd/beta/server/volume/detach/detach.go, internal/cmd/beta/server/volume/detach/detach_test.go, internal/cmd/beta/server/volume/list/list.go, internal/cmd/beta/server/volume/list/list_test.go, internal/cmd/beta/server/volume/update/update.go, internal/cmd/beta/server/volume/update/update_test.go, internal/cmd/beta/server/volume/volume.go
Supported commands: attach, detach, list, describe, update
=> Onboard IaaS server volume commands

docs/stackit_beta_server.md, docs/stackit_beta_server_network-interface.md, docs/stackit_beta_server_network-interface_attach.md, docs/stackit_beta_server_network-interface_detach.md, docs/stackit_beta_server_network-interface_list.md, internal/cmd/beta/server/network-interface/attach/attach.go, internal/cmd/beta/server/network-interface/attach/attach_test.go, internal/cmd/beta/server/network-interface/detach/detach.go, internal/cmd/beta/server/network-interface/detach/detach_test.go, internal/cmd/beta/server/network-interface/list/list.go, internal/cmd/beta/server/network-interface/list/list_test.go, internal/cmd/beta/server/network-interface/network-interface.go, internal/cmd/beta/server/server.go, internal/pkg/errors/errors.go
Supported commands: attach, detach, list
=> Onboard IaaS server network interface commands

docs/stackit_ske_kubeconfig_create.md, internal/cmd/ske/kubeconfig/create/create.go, internal/cmd/ske/kubeconfig/create/create_test.go
- Add flag to disable the writing of kubeconfig
=> Fix: Kubeconfig not written when output format is json

docs/stackit_ske_kubeconfig.md, docs/stackit_ske_kubeconfig_create.md, internal/cmd/ske/kubeconfig/create/create.go, internal/cmd/ske/kubeconfig/create/create_test.go, internal/pkg/services/ske/utils/utils.go, internal/pkg/services/ske/utils/utils_test.go
The PR changes the default behaivor of the command ´ske kubeconfig create´: the kubeconfig information of the SKE cluster is merged into the default kubeconfig file of the current user. If the kubeconfig file doesn't exist, a new one will be created.
https://github.com/stackitcloud/stackit-cli/issues/556
=> feat: ske kubeconfig create. merge kubeconfig into the default kubeconfig file #556 

internal/cmd/beta/network/list/list.go, internal/cmd/beta/security-group/describe/describe.go, internal/cmd/beta/security-group/list/list.go, internal/cmd/beta/security-group/rule/list/list.go, internal/cmd/beta/server/describe/describe.go, internal/cmd/beta/server/list/list.go, internal/cmd/beta/server/list/list_test.go, internal/pkg/utils/utils.go
- `beta network list`
- add value: prefixes
- `beta security-group describe`
- add values
- stateful
- createdAt
- updatedAt
- add "Rules" table with values:
- ID
- description
- protocol
- direction
- etherType
- portRange
- ipRange
- icmpParameters
- remoteSecurityGroupId
- `beta security-group list`
- add values:
- description
- labels
- `beta security-group rule list`
- add value: remoteSecurityGroupId
- `beta server describe`
- add "Maintenance Window" table with values:
- status
- details
- startsAt
- endsAt
- `beta server list`
- add values:
- machineType
- nicIPv4
- publicIPs
=> Extend output of IaaS commands

internal/cmd/beta/network-interface/list/list.go
If no interfaces are attached to the network display the name in the message
=> Fix network-interface output

go.mod, go.sum, internal/cmd/object-storage/bucket/create/create.go, internal/cmd/object-storage/bucket/create/create_test.go, internal/cmd/object-storage/bucket/delete/delete.go, internal/cmd/object-storage/bucket/delete/delete_test.go, internal/cmd/object-storage/bucket/describe/describe.go, internal/cmd/object-storage/bucket/describe/describe_test.go, internal/cmd/object-storage/bucket/list/list.go, internal/cmd/object-storage/bucket/list/list_test.go, internal/cmd/object-storage/credentials-group/create/create.go, internal/cmd/object-storage/credentials-group/create/create_test.go, internal/cmd/object-storage/credentials-group/delete/delete.go, internal/cmd/object-storage/credentials-group/delete/delete_test.go, internal/cmd/object-storage/credentials-group/list/list.go, internal/cmd/object-storage/credentials-group/list/list_test.go, internal/cmd/object-storage/credentials/create/create.go, internal/cmd/object-storage/credentials/create/create_test.go, internal/cmd/object-storage/credentials/delete/delete.go, internal/cmd/object-storage/credentials/delete/delete_test.go, internal/cmd/object-storage/credentials/list/list.go, internal/cmd/object-storage/credentials/list/list_test.go, internal/cmd/object-storage/disable/disable.go, internal/cmd/object-storage/disable/disable_test.go, internal/cmd/object-storage/enable/enable.go, internal/cmd/object-storage/enable/enable_test.go, internal/pkg/services/object-storage/utils/utils.go, internal/pkg/services/object-storage/utils/utils_test.go
- adapted the commands of object-storage to the new region adjustment of `github.com/stackitcloud/stackit-sdk-go/services/objectstorage` v1.0.0
=> feat: region adjustment object storage

docs/stackit_auth.md, docs/stackit_auth_get-access-token.md, internal/cmd/auth/auth.go, internal/cmd/auth/get-access-token/get_access_token.go, internal/pkg/auth/auth.go, internal/pkg/auth/user_token_flow.go, internal/pkg/errors/errors.go
=> feat(auth): add get-access-token cmd

internal/cmd/object-storage/bucket/create/create.go, internal/cmd/object-storage/bucket/create/create_test.go, internal/cmd/object-storage/bucket/describe/describe.go, internal/cmd/object-storage/bucket/describe/describe_test.go, internal/cmd/object-storage/bucket/list/list.go, internal/cmd/object-storage/bucket/list/list_test.go, internal/cmd/object-storage/credentials-group/create/create.go, internal/cmd/object-storage/credentials-group/create/create_test.go, internal/cmd/object-storage/credentials-group/list/list_test.go, internal/cmd/object-storage/credentials/create/create.go, internal/cmd/object-storage/credentials/create/create_test.go, internal/cmd/object-storage/credentials/list/list_test.go
=> fix(object-storage): add nil pointer checks for cmd outputs

internal/cmd/beta/quota/list/list.go, internal/cmd/beta/quota/list/list_test.go
- add tests for the outputResult functions within the quota command
=> fix: stackit beta quota command - add nil pointer checks and tests for the outputResult functions

internal/cmd/beta/public-ip/associate/associate.go, internal/cmd/beta/public-ip/create/create.go, internal/cmd/beta/public-ip/create/create_test.go, internal/cmd/beta/public-ip/delete/delete.go, internal/cmd/beta/public-ip/describe/describe.go, internal/cmd/beta/public-ip/describe/describe_test.go, internal/cmd/beta/public-ip/disassociate/disassociate.go, internal/cmd/beta/public-ip/list/list.go, internal/cmd/beta/public-ip/list/list_test.go
- add tests for the outputResult functions within the public-ip commands
=> fix: stackit beta public-ip commands - add nil pointer checks and tests for the outputResult functions

internal/cmd/beta/image/create/create.go, internal/cmd/beta/image/create/create_test.go, internal/cmd/beta/image/delete/delete.go, internal/cmd/beta/image/describe/describe.go, internal/cmd/beta/image/describe/describe_test.go, internal/cmd/beta/image/list/list.go, internal/cmd/beta/image/list/list_test.go, internal/cmd/beta/image/update/update.go
- add tests for the outputResult functions within the image commands
=> fix: stackit beta image commands - add nil pointer checks and tests for the outputResult functions

internal/cmd/beta/network/create/create.go, internal/cmd/beta/network/create/create_test.go, internal/cmd/beta/network/delete/delete.go, internal/cmd/beta/network/describe/describe.go, internal/cmd/beta/network/describe/describe_test.go, internal/cmd/beta/network/list/list.go, internal/cmd/beta/network/list/list_test.go, internal/cmd/beta/network/update/update.go
- add tests for the outputResult functions within the network commands
=> fix: stackit beta network commands - add nil pointer checks and tests for the outputResult functions

internal/cmd/beta/network-interface/create/create.go, internal/cmd/beta/network-interface/create/create_test.go, internal/cmd/beta/network-interface/describe/describe.go, internal/cmd/beta/network-interface/describe/describe_test.go, internal/cmd/beta/network-interface/list/list.go, internal/cmd/beta/network-interface/list/list_test.go, internal/cmd/beta/network-interface/update/update.go, internal/cmd/beta/network-interface/update/update_test.go
- add tests for the outputResult functions within the `network-interface` commands
=> fix: stackit beta network-interface commands - add nil pointer checks and tests for the outputResult functions

internal/cmd/organization/member/add/add.go, internal/cmd/organization/member/list/list.go, internal/cmd/organization/member/list/list_test.go, internal/cmd/organization/role/list/list.go, internal/cmd/organization/role/list/list_test.go
=> fix(organization): add nil pointer checks for cmd outputs

internal/cmd/opensearch/credentials/create/create.go, internal/cmd/opensearch/credentials/create/create_test.go, internal/cmd/opensearch/credentials/describe/describe.go, internal/cmd/opensearch/credentials/describe/describe_test.go, internal/cmd/opensearch/credentials/list/list_test.go, internal/cmd/opensearch/instance/create/create.go, internal/cmd/opensearch/instance/create/create_test.go, internal/cmd/opensearch/instance/describe/describe.go, internal/cmd/opensearch/instance/describe/describe_test.go, internal/cmd/opensearch/instance/list/list_test.go, internal/cmd/opensearch/plans/plans.go, internal/cmd/opensearch/plans/plans_test.go
=> fix(opensearch): add nil pointer checks for cmd outputs

internal/cmd/mongodbflex/backup/describe/describe.go, internal/cmd/mongodbflex/backup/describe/describe_test.go, internal/cmd/mongodbflex/backup/list/list.go, internal/cmd/mongodbflex/backup/list/list_test.go, internal/cmd/mongodbflex/backup/restore-jobs/restore_jobs_test.go, internal/cmd/mongodbflex/backup/schedule/schedule.go, internal/cmd/mongodbflex/backup/schedule/schedule_test.go, internal/cmd/mongodbflex/instance/create/create.go, internal/cmd/mongodbflex/instance/create/create_test.go, internal/cmd/mongodbflex/instance/describe/describe.go, internal/cmd/mongodbflex/instance/describe/describe_test.go, internal/cmd/mongodbflex/instance/list/list_test.go, internal/cmd/mongodbflex/instance/update/update.go, internal/cmd/mongodbflex/instance/update/update_test.go, internal/cmd/mongodbflex/options/options.go, internal/cmd/mongodbflex/options/options_test.go, internal/cmd/mongodbflex/user/create/create.go, internal/cmd/mongodbflex/user/create/create_test.go, internal/cmd/mongodbflex/user/describe/describe_test.go, internal/cmd/mongodbflex/user/list/list_test.go, internal/cmd/mongodbflex/user/reset-password/reset_password.go, internal/cmd/mongodbflex/user/reset-password/reset_password_test.go
=> fix(mongodbflex): add nil pointer checks for cmd outputs

internal/cmd/observability/credentials/create/create.go, internal/cmd/observability/credentials/create/create_test.go, internal/cmd/observability/credentials/list/list_test.go, internal/cmd/observability/grafana/describe/describe.go, internal/cmd/observability/grafana/describe/describe_test.go, internal/cmd/observability/instance/create/create.go, internal/cmd/observability/instance/create/create_test.go, internal/cmd/observability/instance/describe/describe.go, internal/cmd/observability/instance/describe/describe_test.go, internal/cmd/observability/instance/list/list_test.go, internal/cmd/observability/plans/plans_test.go, internal/cmd/observability/scrape-config/describe/describe.go, internal/cmd/observability/scrape-config/describe/describe_test.go, internal/cmd/observability/scrape-config/generate-payload/generate_payload.go, internal/cmd/observability/scrape-config/generate-payload/generate_payload_test.go, internal/cmd/observability/scrape-config/list/list_test.go
=> fix(observability): add nil pointer checks for cmd outputs

internal/cmd/beta/security-group/create/create.go, internal/cmd/beta/security-group/create/create_test.go, internal/cmd/beta/security-group/describe/describe.go, internal/cmd/beta/security-group/describe/describe_test.go, internal/cmd/beta/security-group/list/list_test.go, internal/cmd/beta/security-group/rule/create/create.go, internal/cmd/beta/security-group/rule/create/create_test.go, internal/cmd/beta/security-group/rule/describe/describe.go, internal/cmd/beta/security-group/rule/describe/describe_test.go, internal/cmd/beta/security-group/rule/list/list_test.go
=> chore(security-group): Add nil pointer checks and tests for the outputResult functions

internal/pkg/auth/user_login.go
In debug mode, print out full authorizationURL to provide workaround when no window-server is available (hence no browser can be opened), as is the case when stackit-cli is run on headless systems.
The workaround is to call
``stackit --verbosity debug auth login``
Copy the link from the debug output and paste it to an available browser.
=> Allow workaround if no browser can be opened

internal/cmd/beta/network-area/create/create.go, internal/cmd/beta/network-area/create/create_test.go, internal/cmd/beta/network-area/delete/delete.go, internal/cmd/beta/network-area/describe/describe.go, internal/cmd/beta/network-area/describe/describe_test.go, internal/cmd/beta/network-area/list/list.go, internal/cmd/beta/network-area/list/list_test.go, internal/cmd/beta/network-area/network-range/create/create.go, internal/cmd/beta/network-area/network-range/create/create_test.go, internal/cmd/beta/network-area/network-range/delete/delete.go, internal/cmd/beta/network-area/network-range/describe/describe.go, internal/cmd/beta/network-area/network-range/describe/describe_test.go, internal/cmd/beta/network-area/network-range/list/list.go, internal/cmd/beta/network-area/network-range/list/list_test.go, internal/cmd/beta/network-area/route/create/create.go, internal/cmd/beta/network-area/route/create/create_test.go, internal/cmd/beta/network-area/route/delete/delete.go, internal/cmd/beta/network-area/route/describe/describe.go, internal/cmd/beta/network-area/route/describe/describe_test.go, internal/cmd/beta/network-area/route/list/list.go, internal/cmd/beta/network-area/route/list/list_test.go, internal/cmd/beta/network-area/route/update/update.go, internal/cmd/beta/network-area/route/update/update_test.go, internal/cmd/beta/network-area/update/update.go, internal/cmd/beta/network-area/update/update_test.go
- add tests for the outputResult functions within the `network-area` commands
=> fix: stackit beta network-area commands - add nil pointer checks and tests for the outputResult functions

internal/cmd/mariadb/credentials/create/create.go, internal/cmd/mariadb/credentials/create/create_test.go, internal/cmd/mariadb/credentials/describe/describe.go, internal/cmd/mariadb/credentials/describe/describe_test.go, internal/cmd/mariadb/credentials/list/list_test.go, internal/cmd/mariadb/instance/create/create.go, internal/cmd/mariadb/instance/create/create_test.go, internal/cmd/mariadb/instance/describe/describe.go, internal/cmd/mariadb/instance/describe/describe_test.go, internal/cmd/mariadb/instance/list/list.go, internal/cmd/mariadb/instance/list/list_test.go, internal/cmd/mariadb/plans/plans.go, internal/cmd/mariadb/plans/plans_test.go
=> fix(mariadb): add nil pointer checks for cmd outputs

internal/cmd/service-account/create/create.go, internal/cmd/service-account/create/create_test.go, internal/cmd/service-account/get-jwks/get_jwks_test.go, internal/cmd/service-account/key/describe/describe.go, internal/cmd/service-account/key/describe/describe_test.go, internal/cmd/service-account/key/list/list_test.go, internal/cmd/service-account/list/list_test.go, internal/cmd/service-account/token/create/create.go, internal/cmd/service-account/token/create/create_test.go, internal/cmd/service-account/token/list/list_test.go
=> fix(service-account): add nil pointer checks for cmd outputs

internal/cmd/ske/cluster/create/create.go, internal/cmd/ske/cluster/create/create_test.go, internal/cmd/ske/cluster/describe/describe.go, internal/cmd/ske/cluster/describe/describe_test.go, internal/cmd/ske/cluster/generate-payload/generate_payload.go, internal/cmd/ske/cluster/generate-payload/generate_payload_test.go, internal/cmd/ske/cluster/list/list.go, internal/cmd/ske/cluster/list/list_test.go, internal/cmd/ske/cluster/update/update.go, internal/cmd/ske/cluster/update/update_test.go, internal/cmd/ske/describe/describe.go, internal/cmd/ske/describe/describe_test.go, internal/cmd/ske/kubeconfig/create/create.go, internal/cmd/ske/kubeconfig/create/create_test.go, internal/cmd/ske/options/options.go, internal/cmd/ske/options/options_test.go
=> fix(ske): add nil pointer checks for cmd outputs

internal/cmd/secrets-manager/instance/create/create.go, internal/cmd/secrets-manager/instance/create/create_test.go, internal/cmd/secrets-manager/instance/describe/describe.go, internal/cmd/secrets-manager/instance/describe/describe_test.go, internal/cmd/secrets-manager/instance/list/list_test.go, internal/cmd/secrets-manager/user/create/create.go, internal/cmd/secrets-manager/user/create/create_test.go, internal/cmd/secrets-manager/user/describe/describe_test.go, internal/cmd/secrets-manager/user/list/list_test.go
=> fix(secrets-manager): add nil pointer checks for cmd outputs

docs/stackit_beta_sqlserverflex_user_create.md, internal/cmd/beta/sqlserverflex/user/create/create.go, internal/cmd/beta/sqlserverflex/user/create/create_test.go
the API requires the roles anyways
relates to STACKITCLI-125
=> fix(sqlserverflex): require roles flag on user creation

go.mod, go.sum, internal/cmd/server/command/create/create.go, internal/cmd/server/command/create/create_test.go, internal/cmd/server/command/describe/describe.go, internal/cmd/server/command/describe/describe_test.go, internal/cmd/server/command/list/list.go, internal/cmd/server/command/list/list_test.go, internal/cmd/server/command/template/describe/describe.go, internal/cmd/server/command/template/describe/describe_test.go, internal/cmd/server/command/template/list/list_test.go, internal/pkg/services/runcommand/client/client.go
=> chore(server): regional adjustment for runcommand

internal/cmd/auth/get-access-token/get_access_token.go
relates to STACKITCLI-175 / #653
=> fix(auth): print token to stdout on get-access-token cmd

INSTALLATION.md
=> chore(doc): update installation docs

README.md, internal/cmd/observability/observability.go
=> chore(observability): remove argus alias and warning in readme

.github/pull_request_template.md, .github/workflows/ci.yaml, scripts/check-docs.sh
=> feat(ci): enusure docs are up-to-date for PRs

.goreleaser.yaml
relates to https://github.com/stackitcloud/homebrew-tap/pull/3
=> feat(goreleaser): add completion to homebrew installation

docs/stackit_image_create.md, internal/cmd/image/create/create.go, internal/cmd/image/create/create_test.go
=> fix(image): Uefi flag cannot be set to false

internal/pkg/print/print.go
=> Fix: Exit less if an interrupt character is typed

internal/cmd/curl/curl.go, internal/cmd/curl/curl_test.go
When using the `stackit curl` command, it's more readable to prettify the JSON response, especially on systems without tools like `jq` or `yq` for easy content extraction. Additionally, I've introduced an error message for expired JWT tokens.
Test it out:
```sh
./bin/stackit curl "https://iaas.api.eu01.stackit.cloud/v1beta1/networks/public-ip-ranges"
./bin/stackit curl "https://iaas.api.eu01.stackit.cloud/v1beta1/networks/public-ip-ranges" | jq
./bin/stackit curl "https://iaas.api.eu01.stackit.cloud/v1beta1/networks/public-ip-ranges" | yq eval '.items[].cidr'
```
Error messages stackit curl:
Old:
New:
=> feat: prettify json output using stackit curl

internal/pkg/auth/user_token_flow.go, internal/pkg/auth/user_token_flow_test.go
This PR fixes a panic, if CLI is authenticated with an invalid Service Account Token.
`stackit auth activate-service-account` accept any JWT token with an email claim. 
However, `stackit auth get-access-token` panics, because the command checks for an expire date, which is not present.
The underlaying JWT library does not return an error, if the exp claim is not present.
JWT RFC explained that exp is an manatory field. However in any case, an application should never panic.
Ref: https://github.com/golang-jwt/jwt/blob/048854f1b0ac96c0a843d52fc09d7878b853683f/map_claims.go#L48
```
stackit auth activate-service-account --service-account-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkdW1teS11c2VyIiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqd2RAZXhhbXBsZS5jb20iLCJpYXQiOjE2MDAwMDAwMDB9.dC8oFS …
```
=> fix panic in auth.TokenExpired

.github/workflows/ci.yaml, .goreleaser.yaml
will help to detect deprecated options
basically the same as https://github.com/stackitcloud/terraform-provider-stackit/pull/863
updated the following deprecated goreleaser options:
- https://goreleaser.com/deprecations/#archivesformat
- https://goreleaser.com/deprecations/#archivesformat_overridesformat
- https://goreleaser.com/deprecations/#nfpmsbuilds
- https://goreleaser.com/deprecations/#snapsbuilds
=> feat(ci): add check for goreleaser configuration

internal/cmd/image/create/create.go, internal/cmd/image/update/update.go, internal/cmd/key-pair/create/create.go, internal/cmd/key-pair/update/update.go, internal/cmd/network-area/create/create.go, internal/cmd/network-area/route/create/create.go, internal/cmd/network-area/route/update/update.go, internal/cmd/network-area/update/update.go, internal/cmd/network-interface/create/create.go, internal/cmd/network-interface/update/update.go, internal/cmd/network/create/create.go, internal/cmd/network/update/update.go, internal/cmd/public-ip/create/create.go, internal/cmd/public-ip/update/update.go, internal/cmd/security-group/create/create.go, internal/cmd/security-group/update/update.go, internal/cmd/server/create/create.go, internal/cmd/server/update/update.go, internal/pkg/utils/utils.go, internal/pkg/utils/utils_test.go
Codebase contained multiple implementations of converting `map[string]string` to `*map[string]interface{}`. This pattern appears in many command files, particularly in the IaaS service commands (volume, backup, network, etc.) when handling label conversions. The code got extracted into util function `ConvertStringMapToInterfaceMap` and refactored.
Jira Ticket: [https://jira.schwarz/browse/STACKITCLI-203](url)
=> refactor(cli): add ConvertStringMapToInterfaceMap util function 

internal/cmd/affinity-groups/delete/delete.go, internal/cmd/image/delete/delete.go, internal/cmd/image/update/update.go, internal/cmd/network-area/delete/delete.go, internal/cmd/network-area/describe/describe.go, internal/cmd/network-area/network-range/delete/delete.go, internal/cmd/network-area/network-range/list/list.go, internal/cmd/network-area/route/create/create.go, internal/cmd/network-area/route/delete/delete.go, internal/cmd/network-area/route/list/list.go, internal/cmd/network-area/route/update/update.go, internal/cmd/server/volume/attach/attach.go, internal/cmd/server/volume/describe/describe.go, internal/cmd/server/volume/detach/detach.go, internal/cmd/server/volume/list/list.go, internal/cmd/server/volume/update/update.go, internal/cmd/volume/delete/delete.go, internal/pkg/services/iaas/utils/utils.go, internal/pkg/services/iaas/utils/utils_test.go
=> fix(iaas): prevent nil pointer dereference on empty volume name

go.mod, go.sum, internal/cmd/ske/cluster/create/create.go, internal/cmd/ske/cluster/create/create_test.go, internal/cmd/ske/cluster/delete/delete.go, internal/cmd/ske/cluster/delete/delete_test.go, internal/cmd/ske/cluster/describe/describe.go, internal/cmd/ske/cluster/describe/describe_test.go, internal/cmd/ske/cluster/generate-payload/generate_payload.go, internal/cmd/ske/cluster/generate-payload/generate_payload_test.go, internal/cmd/ske/cluster/list/list.go, internal/cmd/ske/cluster/list/list_test.go, internal/cmd/ske/cluster/update/update.go, internal/cmd/ske/cluster/update/update_test.go, internal/cmd/ske/credentials/complete-rotation/complete_rotation.go, internal/cmd/ske/credentials/complete-rotation/complete_rotation_test.go, internal/cmd/ske/credentials/start-rotation/start_rotation.go, internal/cmd/ske/credentials/start-rotation/start_rotation_test.go, internal/cmd/ske/kubeconfig/create/create.go, internal/cmd/ske/kubeconfig/create/create_test.go, internal/cmd/ske/kubeconfig/login/login.go, internal/cmd/ske/kubeconfig/login/login_test.go, internal/cmd/ske/options/options.go, internal/cmd/ske/options/options_test.go, internal/pkg/services/ske/client/client.go, internal/pkg/services/ske/utils/utils.go, internal/pkg/services/ske/utils/utils_test.go
=> feat(ske): Region adjustment

internal/cmd/security-group/create/create.go
=> fix: add missing security group ID output to `security-group create` command

internal/cmd/auth/get-access-token/get_access_token.go
=> feat(auth): support output format in stackit auth get-access-token command

internal/cmd/ske/cluster/describe/describe.go, internal/cmd/ske/cluster/describe/describe_test.go
=> feat(ske): show cluster errors in table output

internal/cmd/root.go, internal/cmd/ske/cluster/list/list.go, internal/cmd/ske/cluster/list/list_test.go
also print valid json output when project has no ske clusters
relates to STACKITCLI-240
=> fix(ske): print valid json output when listing clusters

.goreleaser.yaml
Remove `conflicts` configuration for homebrew_casks, because it is deprecated and it's just a no-op. (See [goreleaser docs](https://goreleaser.com/deprecations/#homebrew_casksconflictsformula))
relates to https://github.com/stackitcloud/homebrew-tap/issues/5
=> fix(goreleaser): Remove conflicts configuration for homebrew_casks

.aptly.conf
=> fix: s3 publish endpoint could not be parsed

.goreleaser.yaml, INSTALLATION.md, README.md, docs/stackit.md, internal/cmd/root.go, internal/pkg/auth/templates/login-successful.html
=> chore(cli): Move stackit cli to GA

.goreleaser.yaml
relates to https://github.com/stackitcloud/homebrew-tap/issues/8
The completions files weren't part of the linux archives, which results in an error when installing the STACKIT CLI via homebrew on linux
=> fix: add completions to linux archives
